name: "beige_hoodie"
cloth_model_file_name: "Beige_Hoodie/beige_hoodie_25k.obj"
cloth_model_usda: "Beige_Hoodie/beige_hoodie_25k.usda"
# appearance properties
rgba: [0.70, 0.69, 0.65, 1]

# physical properties of the cloth
stretch: 660000
bending: 5000
density: 390
friction: 0.266
kinetic_friction: 0.025
damping: 0.1
mass: 0.255 # kg //TODO: check mass value
poisson: 0.35

# key indices for the cloth model
shoulder_index: [4445, 1232]  # indices of the shoulder points