name: "grey_sunwear"
cloth_model_file_name: "Grey_Sunwear/grey_sunwear.obj"
cloth_model_usda: "Grey_Sunwear/grey_sunwear.usda"
# appearance properties
rgba: [0.655, 0.654, 0.643, 1.0]

# physical properties of the cloth
stretch: 1000000
bending: 850
density: 110.61
friction: 0.266
kinetic_friction: 0.025
damping: 0.1
mass: 0.255 # kg
poisson: 0.35

# key indices for the cloth model
shoulder_index: [22261, 19654]  # indices of the shoulder points