name: "white_shirt"
cloth_model_file_name: "White_Shirt/white_shirt_30k.obj"
cloth_model_usda: "White_Shirt/white_shirt_30k.usda"
# appearance properties
rgba: [0.95, 0.92, 0.85, 1.0]

# physical properties of the cloth
stretch: 1000000
bending: 1500
density: 167
friction: 0.266
kinetic_friction: 0.025
damping: 0.1
mass: 0.255 # kg
poisson: 0.35

# key indices for the cloth model
shoulder_index: [3559, 8814]  # indices of the shoulder points
